Repository jenkins-x/dev-env-base, pull requests merged in 2019-07, with the labels that each got.

#28 chore: Add macox to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#27 chore: Upgrade jx to 2.0.368
  Dockerfile.go-alpine
Labels: approved, size/XS

#43 feat: Auto update dev-env with base version
  jenkins-x.yml
  scripts/update-bot.sh
Labels: approved, size/S

#45 fix: Executable perms for update-bot script
  scripts/update-bot.sh
Labels: approved, size/XS

#46 fix: Use https url for update-bot repo
  scripts/update-bot.sh
Labels: approved, size/XS

#53 fix: Use jx-builder image for update-bot
  jenkins-x.yml
Labels: approved, size/XS

#54 fix: update-bot jx path
  scripts/update-bot.sh
Labels: approved, size/XS

#57 chore: Upgrade helm 2.14.1
  Dockerfile.go-alpine
  Dockerfile.go-stretch
Labels: approved, size/XS

#58 chore: Upgrade kubectl 1.15.0
  Dockerfile.go-alpine
  Dockerfile.go-stretch
Labels: approved, size/XS

#59 chore: Upgrade gcloud to 252.0.0
  Dockerfile.go-alpine
  Dockerfile.go-stretch
Labels: approved, size/XS

#64 chore: Remove non required Dockerfile
  Dockerfile
Labels: approved, size/XS

#65 feat: Deprecating the stretch image of the dev-env-base
  Dockerfile.go-stretch
  Makefile
  README.md
  jenkins-x.yml
Labels: approved, size/L

#67 chore: Update base image to 1.12.6-alpine3.10
  Dockerfile.go-alpine
Labels: approved, size/XS

#69 fix: Moved install of pre-commit
  Dockerfile.go-alpine
Labels: approved, size/XS

#74 feat: Install detect secrets
  Dockerfile.go-alpine
Labels: approved, size/S

#76 feat: add bash completion to jx
  env/bashrc
Labels: approved, size/XS

#75 feat: adding terraform vim plugin
  Dockerfile.go-alpine
  README.md
Labels: approved, size/XS

#72 chore: add changelog.sh
  jenkins-x.yml
  scripts/changelog.sh
Labels: approved, size/XS

#78 fix: made changelog.sh executable
  scripts/changelog.sh
Labels: approved, size/XS

#81 feat: added gcloud alpha and beta components
  Dockerfile.go-alpine
Labels: approved, size/XS

#84 feat: install yamale
  Dockerfile.go-alpine
Labels: approved, size/XS

#82 fix: Added missing hyphen in version option
  scripts/changelog.sh
Labels: approved, size/XS

#85 feat: Improving how multistaged images are built
  Dockerfile.go-alpine
  Makefile
Labels: approved, size/M

#86 fix: Revert "feat: Improving how multistaged images are built"
  Dockerfile.go-alpine
  Makefile
Labels: approved, size/M

#93 feat: now able to have a k8s context per window session
  env/bashrc
  env/tmux.conf.local
Labels: approved, size/S

#94 fix: remove vi as the default terminal prompt editor
  env/bashrc
Labels: approved, size/XS

#95 feat: add zip and findutils for newer xargs
  Dockerfile.go-alpine
Labels: approved, size/XS

#105 chore: create release notes first
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#106 chore: update builder to prevent double tagging
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#119 chore: Add memory requests/limits to pipeline
  jenkins-x.yml
Labels: approved, size/S

#123 fix: resolve tmux window number retrieval
  env/bashrc
Labels: approved, size/XS

#128 revert: removed kube session per tmux window
  env/bashrc
  env/tmux.conf.local
Labels: approved, size/S

#145 chore: added .secrets.baseline
  .secrets.baseline
Labels: approved, lgtm, size/M
