Repository jenkins-x/dev-env-base, pull requests merged in 2019-08, with the labels that each got.

#177 fix: add missing pipeline build for zsh container base
  jenkins-x.yml
Labels: approved, size/S

#179 fix: update the dev-env-zsh file with the new version
  scripts/update-bot.sh
Labels: approved, size/XS

#188 chore: remove gcloud version arg
  Dockerfile.go-alpine
Labels: approved, size/XS

#187 chore: remove version args
  Dockerfile.go-alpine
Labels: approved, size/XS

#225 fix: update cluster name
  env/bash/tmux.conf.local
Labels: approved, size/XS

#200 feat: reduced down to 1 dockerfile and parameterised to improve maint…
  Dockerfile.go-alpine
  Dockerfile.go-alpine-zsh
  Makefile
  env/zsh/tmux.conf.local
  jenkins-x.yml
Labels: approved, size/L

#245 feat: added vault client and diffutils
  Dockerfile.go-alpine
Labels: approved, size/XS

#246 feat: add the safe vault client
  Dockerfile.go-alpine
Labels: approved, size/XS

#255 feat: Added bind-tools package for dig/nslookup
  Dockerfile.go-alpine
Labels: approved, size/XS

#258 fix: reduced image size
  Dockerfile.go-alpine
  Makefile
Labels: approved, size/S
